name: Prisma DB Push to Development Database

on:
  push:
    branches: [development]
    paths: ["prisma/**"]

jobs:
  db-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install Prisma CLI
        run: npm install -g prisma
      - name: Install dependencies
        run: npm install
      - name: Generate Prisma Client
        run: npx prisma generate
      - name: Prisma DB Push
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma db push
